// src/data.js

export const translations = {
    en: {
      name1: "Stefan Jelkić",
      name2: "Nikola Matosić",
      subtitle: "We build full-stack web solutions.",
      aboutTitle: "About",
      aboutText1:
        "We are Stefan Jelkić and Nikola Matosić, founders of IT Solutions, a brand we aim to grow into a leading software development company. Based in Novi Sad, Serbia, we specialize in creating full-stack web applications and websites tailored to businesses of all sizes, driven by our passion for technology and innovation.",
      aboutText2:
        "Graduates of the Faculty of Technical Sciences in Novi Sad, we hold degrees in Software and Information Technologies and are pursuing master’s degrees in Engineering Management. Our expertise in programming, system design, and project management allows us to deliver scalable, efficient solutions while meeting client expectations through clear communication and competitive pricing.",
      aboutText3:
        "Our goal is to expand IT Solutions and establish a reputation for quality and creativity. We adapt to diverse industries, ensuring client satisfaction with every project. Outside work, we explore new technologies, work on personal projects, and enjoy nature and travel, which fuels our inspiration and growth.",
      technologiesTitle: "Technologies we use",
      projectsTitle: "Projects & Experience",
      teamProjectsTitle: "Team Projects",
      stefanProjectsTitle: "Stefan's personal Projects & Experience",
      nikolaProjectsTitle: "Nikola's personal Projects & Experience",
      comingSoon: "Coming soon...",
      techShopTitle: "Tech Shop",
      techShopDesc:
        "The website is used for selling technology products. Data can be searched and filtered by categories. Cart functionalities and order functionalities. Admin control of workflows. Adding discounts for specific users and more.",
      ftnStudentServiceTitle: "FTN Student Service",
      ftnStudentServiceDesc:
        "An internal project demonstrating the student service at FTN. Students are enrolled in programs and have courses they take. Professors grade their students in courses and apply for new courses. Admin CRUD operations and more.",
      travelAdvisorTitle: "Travel Advisor",
      travelAdvisorDesc:
        "Travel Advisor website I used as my thesis project at university. The purpose of the application is to display all destinations with comments from other users and reactions to those comments. Google Maps were used for destinations and more.",
      internshipTitle: "实习 at PR Presiva Novi Sad",
      internshipDesc:
        "Training in client communication and working on internal team projects (company planner, plan, and program).",
      period1: "02.2025 - 04.2025",
      period2: "01.2025 - 03.2025",
      period3: "05.2024 - 07.2024",
      period4: "04.2024 - 05.2024",
      navAbout: "About",
      navTechnologies: "Technologies",
      navProjects: "Projects & Experiences",
      githubStefan: "Stefan's GitHub",
      githubNikola: "Nikola's GitHub",
      contactStefan: "Stefan - +381695590320",
      contactNikola: "Nikola - +381646477555",
      languageButton: "Serbian",
    },
    sr: {
      name1: "Stefan Jelkić",
      name2: "Nikola Matosić",
      subtitle: "Gradimo kompletna web rešenja.",
      aboutTitle: "O nama",
      aboutText1:
        "Mi smo Stefan Jelkić i Nikola Matosić, osnivači IT Solutions, brenda koji želimo da razvijemo u vodeću kompaniju za razvoj softvera. Sa sedištem u Novom Sadu, Srbija, specijalizovani smo za kreiranje kompletnih web aplikacija i web sajtova prilagođenih preduzećima svih veličina, vođeni našom strašću prema tehnologiji i inovacijama.",
      aboutText2:
        "Diplomci Fakulteta tehničkih nauka u Novom Sadu, posedujemo diplome iz softverskih i informacionih tehnologija i trenutno pohađamo master studije iz inženjerskog menadžmenta. Naša stručnost u programiranju, sistemskom dizajnu i upravljanju projektima omogućava nam da isporučimo skalabilna, efikasna rešenja uz ispunjavanje očekivanja klijenata kroz jasnu komunikaciju i konkurentne cene.",
      aboutText3:
        "Naš cilj je da proširimo IT Solutions i izgradimo reputaciju za kvalitet i kreativnost. Prilagođavamo se različitim industrijama, obezbeđujući zadovoljstvo klijenata sa svakim projektom. Izvan posla, istražujemo nove tehnologije, radimo na ličnim projektima i uživamo u prirodi i putovanjima, što podstiče našu inspiraciju i rast.",
      technologiesTitle: "Tehnologije koje koristimo",
      projectsTitle: "Projekti i iskustvo",
      teamProjectsTitle: "Timski projekti",
      stefanProjectsTitle: "Stefanovi lični projekti i iskustvo",
      nikolaProjectsTitle: "Nikolini lični projekti i iskustvo",
      comingSoon: "Uskoro dolazi...",
      techShopTitle: "Tech Shop",
      techShopDesc:
        "Web sajt se koristi za prodaju tehnoloških proizvoda. Podaci se mogu pretraživati i filtrirati po kategorijama. Funkcionalnosti korpe i naručivanja. Administratorska kontrola tokova rada. Dodavanje popusta za određene korisnike i još mnogo toga.",
      ftnStudentServiceTitle: "Studentska služba FTN",
      ftnStudentServiceDesc:
        "Interni projekat koji prikazuje studentsku službu na FTN-u. Studenti su upisani na programe i pohađaju kurseve. Profesori ocenjuju studente na kursevima i prijavljuju se za nove kurseve. Administratorske CRUD operacije i još mnogo toga.",
      travelAdvisorTitle: "Travel Advisor",
      travelAdvisorDesc:
        "Web sajt Travel Advisor koji sam koristio kao diplomski rad na univerzitetu. Svrha aplikacije je da prikaže sve destinacije sa komentarima korisnika i reakcijama na te komentare. Google Maps su korišćeni za destinacije i još mnogo toga.",
      internshipTitle: "Praksa u PR Presiva Novi Sad",
      internshipDesc:
        "Obuka u komunikaciji sa klijentima i rad na internim timskim projektima (planiranje kompanije, plan i program).",
      period1: "02.2025 - 04.2025",
      period2: "01.2025 - 03.2025",
      period3: "05.2024 - 07.2024",
      period4: "04.2024 - 05.2024",
      navAbout: "O nama",
      navTechnologies: "Tehnologije",
      navProjects: "Projekti i iskustvo",
      githubStefan: "Stefanov GitHub",
      githubNikola: "Nikolin GitHub",
      contactStefan: "Stefan - +381695590320",
      contactNikola: "Nikola - +381646477555",
      languageButton: "English",
    },
  };
  
  export const techStack = [
    "Java",
    "Spring Boot",
    "Spring Security",
    "JWT",
    ".NET",
    "ASP.NET",
    "C#",
    "JavaScript",
    "TypeScript",
    "React",
    "React.js",
    "React Native",
    "Redux",
    "Axios",
    "Next.js",
    "Node.js",
    "HTML",
    "HTML5",
    "CSS",
    "Bootstrap",
    "Tailwind",
    "MySQL",
    "PostgreSQL",
    "MSSQL",
    "Elasticsearch",
    "Docker",
    "Git",
    "GitHub",
    "Google Maps API",
  ];
  
  export const teamProjects = [];
  
  export const stefanProjects = [
    {
      title: "techShopTitle",
      description: "techShopDesc",
      tech: [
        "Spring Boot",
        "React",
        "MySQL",
        "Java",
        "Spring Security",
        "JWT",
        "JavaScript",
        "React.js",
        "Axios",
        "HTML",
        "CSS",
        "Bootstrap",
        "Elasticsearch",
        "Docker",
        "Git",
        "GitHub",
      ],
      github: "https://github.com/stefanjelkic00/tech-shop",
      type: "project",
      period: "period1",
    },
    {
      title: "ftnStudentServiceTitle",
      description: "ftnStudentServiceDesc",
      tech: [
        "React",
        "JWT",
        ".NET",
        "ASP.NET",
        "C#",
        "JavaScript",
        "React.js",
        "Axios",
        "HTML",
        "HTML5",
        "CSS",
        "Bootstrap",
        "MSSQL",
        "Git",
        "GitHub",
      ],
      github: "https://github.com/stefanjelkic00/ftn-student-service",
      type: "project",
      period: "period2",
    },
    {
      title: "travelAdvisorTitle",
      description: "travelAdvisorDesc",
      tech: [
        "React",
        "Spring Boot",
        "Google Maps API",
        "Java",
        "Spring Security",
        "JWT",
        "JavaScript",
        "React.js",
        "Axios",
        "HTML",
        "CSS",
        "Bootstrap",
        "MySQL",
        "Git",
        "GitHub",
      ],
      github: "https://github.com/stefanjelkic00/travel-advisor",
      type: "project",
      period: "period3",
    },
    {
      title: "internshipTitle",
      description: "internshipDesc",
      period: "period4",
      tech: [
        "Java",
        "Spring Boot",
        "Spring Security",
        "JWT",
        "JavaScript",
        "React",
        "React.js",
        "Axios",
        "HTML",
        "CSS",
        "Bootstrap",
        "MySQL",
        "Git",
        "Docker",
      ],
      type: "experience",
    },
  ];
  
  export const nikolaProjects = [];
  
  export const navItems = [
    { id: "about", label: "navAbout" },
    { id: "technologies", label: "navTechnologies" },
    { id: "projects", label: "navProjects" },
  ];