// src/styles.js

export const styles = {
  logoSpotlightContainer: {
    position: "relative",
    display: "inline-block",
  },
  logoSpotlight: (theme) => ({
    position: "absolute",
    width: "900px",
    height: "900px",
    background:
      theme === "dark"
        ? "radial-gradient(circle, rgba(255, 166, 0, 0.1) 0%, transparent 70%)"
        : "radial-gradient(circle, rgba(0, 0, 0, 0.3) 0%, transparent 70%)",
    borderRadius: "50%",
    pointerEvents: "none",
    zIndex: "-1",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    opacity: "0.8",
    transition: "background 0.3s ease",
  }),
  container: (theme) => ({
    display: "flex",
    minHeight: "100vh",
    backgroundColor: theme === "dark" ? "#0d0d0d" : "#f5f5f5",
    backgroundImage: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' stroke='${
      theme === "dark" ? "%23000000" : "%23666666"
    }' stroke-width='1' stroke-opacity='0.1'%3E%3Cpath d='M0 60L60 0'/%3E%3C/g%3E%3C/svg%3E")`,
    backgroundAttachment: "fixed",
    backgroundSize: "60px 60px",
    color: theme === "dark" ? "#ffffff" : "#333333",
    position: "relative",
    zIndex: 0,
  }),
  leftSide: (theme) => ({
    width: "40%",
    position: "fixed",
    top: 0,
    left: 0,
    height: "100vh",
    display: "flex",
    alignItems: "center",
    padding: "0 2rem",
    backgroundColor: "transparent",
    zIndex: 1,
  }),
  leftContent: {
    maxWidth: "500px",
    textAlign: "left",
  },
  logo: (theme) => ({
    width: "100px",
    height: "100px",
    marginBottom: "1rem",
    borderRadius: "50%",
    objectFit: "cover",
    border: `2px solid ${theme === "dark" ? "#ffa500" : "#ff6200"}`,
    position: "relative",
    zIndex: 2,
  }),
  name: (theme) => ({
    fontSize: "2.7rem",
    fontWeight: "bold",
    marginBottom: "0.3rem",
    color: theme === "dark" ? "#ffffff" : "#333333",
  }),
  subtitle: (theme) => ({
    fontSize: "1.5rem",
    color: theme === "dark" ? "#ccc" : "#666",
    margin: "1rem 0",
  }),
  desc: (theme) => ({
    fontSize: "1rem",
    color: theme === "dark" ? "#aaa" : "#555",
    lineHeight: "1.6",
    marginBottom: "1rem",
  }),
  rightSide: {
    width: "60%",
    marginLeft: "40%",
    overflowY: "auto",
    padding: "2rem",
    paddingTop: "120px",
  },
  nav: {
    marginTop: "2rem",
  },
  navList: {
    listStyle: "none",
    padding: "0",
    margin: "0",
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  navLink: (theme) => ({
    background: "none",
    border: "none",
    color: theme === "dark" ? "#ccc" : "#666",
    fontSize: "1.1rem",
    cursor: "pointer",
    textDecoration: "none",
    padding: "0",
    position: "relative",
    textAlign: "left",
    transition: "all 0.3s ease",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  }),
  navLinkBefore: (theme) => ({
    content: '""',
    width: "20px",
    height: "1px",
    backgroundColor: theme === "dark" ? "#ccc" : "#666",
    transition: "all 0.3s ease",
  }),
  navLinkHover: (theme) => ({
    color: theme === "dark" ? "#ffa500" : "#ff6200",
  }),
  navLinkHoverBefore: (theme) => ({
    backgroundColor: theme === "dark" ? "#ffa500" : "#ff6200",
  }),
  socials: {
    marginTop: "2rem",
  },
  socialIcons: {
    display: "flex",
    gap: "1rem",
    marginBottom: "1rem",
  },
  socialLink: (theme) => ({
    color: theme === "dark" ? "#ccc" : "#666",
    transition: "color 0.3s",
    cursor: "pointer",
  }),
  socialLinkHover: (theme) => ({
    color: theme === "dark" ? "#ffa500" : "#ff6200",
  }),
  languageText: {
    fontSize: "25px",
    lineHeight: "25px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "25px",
    height: "25px",
  },
  githubList: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    marginBottom: "1rem",
  },
  githubLink: (theme) => ({
    color: theme === "dark" ? "#ccc" : "#666",
    fontSize: "0.9rem",
    textDecoration: "none",
    transition: "color 0.3s",
  }),
  githubLinkHover: (theme) => ({
    color: theme === "dark" ? "#ffa500" : "#ff6200",
  }),
  emailList: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    marginBottom: "1rem",
  },
  emailLink: (theme) => ({
    color: theme === "dark" ? "#ccc" : "#666",
    fontSize: "0.9rem",
    textDecoration: "none",
    transition: "color 0.3s",
  }),
  emailLinkHover: (theme) => ({
    color: theme === "dark" ? "#ffa500" : "#ff6200",
  }),
  contactList: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    marginBottom: "1rem",
  },
  contactItem: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  contactIcons: {
    display: "flex",
    gap: "0.5rem",
  },
  contactIcon: (theme) => ({
    color: theme === "dark" ? "#ccc" : "#666",
    transition: "color 0.3s",
  }),
  contactText: (theme) => ({
    color: theme === "dark" ? "#ccc" : "#666",
    fontSize: "0.9rem",
    margin: 0,
  }),
  section: {
    marginBottom: "8rem",
  },
  heading: (theme) => ({
    fontSize: "2.5rem",
    color: theme === "dark" ? "#ffa500" : "#ff6200",
    marginBottom: "2rem",
    letterSpacing: "1px",
    textShadow: theme === "dark" ? "1px 1px 2px rgba(0, 0, 0, 0.3)" : "none",
  }),
  subSection: {
    marginBottom: "3rem",
  },
  subHeading: (theme) => ({
    fontSize: "1.8rem",
    color: theme === "dark" ? "#ffa500" : "#ff6200",
    marginBottom: "1.5rem",
    letterSpacing: "1px",
    textShadow: theme === "dark" ? "1px 1px 2px rgba(0, 0, 0, 0.3)" : "none",
  }),
  emptyMessage: (theme) => ({
    fontSize: "1rem",
    color: theme === "dark" ? "#aaa" : "#555",
    fontStyle: "italic",
  }),
  techGrid: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.6rem",
  },
  techBadge: (theme) => ({
    backgroundColor: theme === "dark" ? "#1e1e1e" : "#e0e0e0",
    color: theme === "dark" ? "#ffa500" : "#ff6200",
    padding: "0.4rem 0.9rem",
    borderRadius: "4px",
    fontSize: "0.85rem",
    border: `1px solid ${theme === "dark" ? "#ffa500" : "#ff6200"}`,
  }),
  grid: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: "2rem",
  },
  card: (theme) => ({
    backgroundColor: theme === "dark" ? "transparent" : "#ffffff",
    borderRadius: "8px",
    padding: "2rem",
    boxShadow: theme === "dark" ? "none" : "0 2px 8px rgba(0, 0, 0, 0.1)",
    transition: "0.3s",
    width: "100%",
    maxWidth: "600px",
    margin: "0 auto",
    position: "relative",
  }),
  cardHeader: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    marginBottom: "0.5rem",
  },
  link: (theme) => ({
    color: theme === "dark" ? "#ffa500" : "#ff6200",
    fontSize: "1.1rem",
    fontWeight: "bold",
    textDecoration: "none",
  }),
  period: (theme) => ({
    fontSize: "0.9rem",
    color: theme === "dark" ? "#ccc" : "#666",
    marginBottom: "0.5rem",
    fontStyle: "italic",
  }),
  description: (theme) => ({
    fontSize: "0.95rem",
    color: theme === "dark" ? "#aaa" : "#555",
    marginBottom: "1rem",
    lineHeight: "1.5",
  }),
  techStack: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.5rem",
  },
  arrowIcon: (theme) => ({
    position: "absolute",
    top: "1rem",
    right: "1rem",
    color: theme === "dark" ? "#ccc" : "#666",
    transition: "color 0.3s",
  }),
  themeToggle: (theme) => ({
    color: theme === "dark" ? "#ccc" : "#666",
    transition: "color 0.3s",
    cursor: "pointer",
  }),
};