// src/styles.js
export const styles = {
  container: (theme, isMobile = false) => ({
    display: "flex",
    minHeight: "100vh",
    backgroundColor: theme === "dark" ? "#0d0d0d" : "#f5f5f5",
    backgroundImage: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' stroke='${
      theme === "dark" ? "%23000000" : "%23666666"
    }' stroke-width='1' stroke-opacity='0.1'%3E%3Cpath d='M0 60L60 0'/%3E%3C/g%3E%3C/svg%3E")`,
    backgroundAttachment: "fixed",
    backgroundSize: "60px 60px",
    color: theme === "dark" ? "#ffffff" : "#333333",
    position: "relative",
    zIndex: 0,
    flexDirection: isMobile ? "column" : "row",
  }),
  leftSide: (theme, isMobile = false) => ({
    width: isMobile ? "100%" : "40%",
    position: isMobile ? "relative" : "fixed",
    top: isMobile ? "auto" : 0,
    left: isMobile ? "auto" : 0,
    height: isMobile ? "auto" : "100vh",
    display: "flex",
    alignItems: isMobile ? "flex-start" : "center",
    padding: isMobile ? "1rem" : "0 2rem",
    backgroundColor: isMobile ? (theme === "dark" ? "#1a1a1a" : "#ffffff") : "transparent",
    zIndex: 1,
    boxShadow: isMobile ? (theme === "dark" ? "0 2px 5px rgba(0,0,0,0.5)" : "0 2px 5px rgba(0,0,0,0.1)") : "none",
  }),
  leftContent: (isMobile = false) => ({
    maxWidth: isMobile ? "100%" : "500px",
    textAlign: isMobile ? "center" : "left",
    width: "100%",
  }),
  rightSide: (isMobile = false) => ({
    width: isMobile ? "100%" : "60%",
    marginLeft: isMobile ? 0 : "40%",
    overflowY: "auto",
    padding: isMobile ? "1rem" : "2rem",
    paddingTop: isMobile ? "1rem" : "120px",
  }),
  logoSpotlightContainer: {
    position: "relative",
    display: "inline-block",
  },
  logo: (theme, isMobile = false) => ({
    width: isMobile ? "80px" : "100px",
    height: isMobile ? "80px" : "100px",
    marginBottom: "1rem",
    borderRadius: "50%",
    objectFit: "cover",
    border: `2px solid ${theme === "dark" ? "#ffa500" : "#ff6200"}`,
    position: "relative",
    zIndex: 2,
    margin: isMobile ? "0 auto 1rem" : "0 0 1rem",
  }),
  logoSpotlight: (theme) => ({
    content: "''",
    position: "absolute",
    top: "-10px",
    left: "-10px",
    right: "-10px",
    bottom: "-10px",
    background: `radial-gradient(circle, ${
      theme === "dark" ? "rgba(255, 165, 0, 0.3)" : "rgba(255, 98, 0, 0.3)"
    } 0%, transparent 70%)`,
    zIndex: 1,
    borderRadius: "50%",
  }),
  name: (theme, isMobile = false) => ({
    fontSize: isMobile ? "1.8rem" : "2.7rem",
    fontWeight: "bold",
    marginBottom: "0.3rem",
    color: theme === "dark" ? "#ffffff" : "#333333",
  }),
  subtitle: (theme, isMobile = false) => ({
    fontSize: isMobile ? "1.2rem" : "1.5rem",
    color: theme === "dark" ? "#ccc" : "#666",
    margin: "1rem 0",
  }),
  desc: (theme, isMobile) => ({
    fontSize: isMobile ? "1rem" : "1.1rem",
    lineHeight: 1.6,
    color: theme === "dark" ? "#d1d5db" : "#4b5563",
    marginTop: "1rem",
  }),
  teamDesc: (theme, isMobile) => ({
    fontSize: isMobile ? "1.1rem" : "1.2rem",
    lineHeight: 1.6,
    color: theme === "dark" ? "#e5e7eb" : "#374151",
    marginTop: "1rem",
    fontWeight: 500,
  }),
  nav: (isMobile = false) => ({
    marginTop: isMobile ? "1rem" : "2rem",
    display: isMobile ? "none" : "block",
  }),
  navList: (isMobile = false) => ({
    listStyle: "none",
    padding: "0",
    margin: "0",
    display: "flex",
    flexDirection: isMobile ? "column" : "column",
    gap: "1rem",
  }),
  navLink: (theme, isMobile = false) => ({
    background: "none",
    border: "none",
    color: theme === "dark" ? "#ccc" : "#666",
    fontSize: isMobile ? "1rem" : "1.1rem",
    cursor: "pointer",
    textDecoration: "none",
    padding: isMobile ? "0.5rem 0" : "0",
    position: "relative",
    textAlign: isMobile ? "center" : "left",
    transition: "all 0.3s ease",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    minHeight: "48px",
    outline: "none",
  }),
  navLinkHover: (theme) => ({
    color: theme === "dark" ? "#ffa500" : "#ff6200",
  }),
  navLinkBefore: (theme) => ({
    content: "''",
    position: "absolute",
    left: "-45px",
    width: "20px",
    height: "2px",
    backgroundColor: theme === "dark" ? "#ccc" : "#666",
    transition: "all 0.3s ease",
  }),
  navLinkHoverBefore: (theme) => ({
    backgroundColor: theme === "dark" ? "#ffa500" : "#ff6200",
  }),
  socials: (isMobile = false) => ({
    marginTop: isMobile ? "1rem" : "2rem",
  }),
  socialIcons: (isMobile = false) => ({
    display: "flex",
    gap: isMobile ? "0.8rem" : "1rem",
    marginBottom: "1rem",
    justifyContent: isMobile ? "center" : "flex-start",
  }),
  socialLink: (theme, isMobile = false) => ({
    color: theme === "dark" ? "#ccc" : "#666",
    transition: "color 0.3s",
    cursor: "pointer",
    fontSize: isMobile ? "1.5rem" : "1rem",
    padding: "10px",
  }),
  socialLinkHover: (theme) => ({
    color: theme === "dark" ? "#ffa500" : "#ff6200",
  }),

  githubList: (isMobile = false) => ({
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    marginBottom: "1rem",
    justifyContent: isMobile ? "center" : "flex-start",
    alignItems: isMobile ? "center" : "flex-start",
    width: "100%",
  }),
  githubLink: (theme, isMobile = false) => ({
    color: theme === "dark" ? "#ccc" : "#666",
    textDecoration: "none",
    fontSize: isMobile ? "0.95rem" : "0.9rem",
    transition: "color 0.3s, transform 0.3s",
    textAlign: isMobile ? "center" : "left",
  }),

  githubLinkHover: (theme) => ({
    color: theme === "dark" ? "#ffa500" : "#ff6200",
  }),
  emailList: (isMobile = false) => ({
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    marginBottom: "1rem",
    justifyContent: isMobile ? "center" : "flex-start",
    alignItems: isMobile ? "center" : "flex-start",
    width: "100%",
  }),
  emailLink: (theme, isMobile = false) => ({
    color: theme === "dark" ? "#ccc" : "#666",
    textDecoration: "none",
    fontSize: isMobile ? "0.95rem" : "0.9rem",
    transition: "color 0.3s, transform 0.3s",
    textAlign: isMobile ? "center" : "left",
  }),
  emailLinkHover: (theme) => ({
    color: theme === "dark" ? "#ffa500" : "#ff6200",
  }),
  contactList: (isMobile = false) => ({
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    justifyContent: isMobile ? "center" : "flex-start",
    alignItems: isMobile ? "center" : "flex-start",
    width: "100%",
  }),
  contactItem: (isMobile = false) => ({
    display: "flex",
    flexDirection: "row",
    gap: isMobile ? "1rem" : "2rem",
    alignItems: "center",
    justifyContent: isMobile ? "center" : "flex-start",
    width: isMobile ? "100%" : "auto",
    textAlign: isMobile ? "center" : "left",
  }),
  contactText: (theme, isMobile = false) => ({
    color: theme === "dark" ? "#ccc" : "#666",
    fontSize: isMobile ? "0.95rem" : "0.9rem",
    margin: 0,
    textAlign: isMobile ? "center" : "left",
  }),
  contactIcons: {
    display: "flex",
    gap: "1rem",
  },
  contactIcon: (theme) => ({
    color: theme === "dark" ? "#ccc" : "#666",
    transition: "color 0.3s",
  }),
  themeToggle: (theme, isMobile = false) => ({
    color: theme === "dark" ? "#ccc" : "#666",
    cursor: "pointer",
    fontSize: isMobile ? "1.5rem" : "1rem",
    padding: "10px",
    transition: "color 0.3s",
  }),
  languageText: (isMobile = false) => ({
    fontSize: isMobile ? "1rem" : "0.8rem",
    fontWeight: "bold",
  }),
  section: (isMobile = false) => ({
    marginBottom: isMobile ? "4rem" : "8rem",
  }),
  heading: (theme, isMobile = false) => ({
    fontSize: isMobile ? "1.8rem" : "2.5rem",
    color: theme === "dark" ? "#ffa500" : "#ff6200",
    marginBottom: "1.5rem",
    letterSpacing: "1px",
    textShadow: theme === "dark" ? "1px 1px 2px rgba(0, 0, 0, 0.3)" : "none",
  }),
  subSection: {
    marginBottom: "3rem",
  },
  subHeading: (theme) => ({
    fontSize: "1.8rem",
    color: theme === "dark" ? "#ffa500" : "#ff6200",
    marginBottom: "1.5rem",
    letterSpacing: "1px",
    textShadow: theme === "dark" ? "1px 1px 2px rgba(0, 0, 0, 0.3)" : "none",
  }),
  emptyMessage: (theme) => ({
    fontSize: "1rem",
    color: theme === "dark" ? "#aaa" : "#555",
    fontStyle: "italic",
  }),
  techGrid: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.6rem",
  },
  techBadge: (theme) => ({
    backgroundColor: theme === "dark" ? "#1e1e1e" : "#e0e0e0",
    color: theme === "dark" ? "#ffa500" : "#ff6200",
    padding: "0.4rem 0.9rem",
    borderRadius: "4px",
    fontSize: "0.85rem",
    border: `1px solid ${theme === "dark" ? "#ffa500" : "#ff6200"}`,
  }),
  grid: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: "2rem",
  },
  card: (theme, isMobile = false) => ({
    backgroundColor: theme === "dark" ? "transparent" : "#ffffff",
    borderRadius: "8px",
    padding: isMobile ? "1rem" : "2rem",
    boxShadow: theme === "dark" ? "none" : "0 2px 8px rgba(0, 0, 0, 0.1)",
    transition: "0.3s",
    width: "100%",
    maxWidth: isMobile ? "100%" : "600px",
    margin: "0 auto",
    position: "relative",
  }),
  link: (theme) => ({
    color: theme === "dark" ? "#ffa500" : "#ff6200",
    fontSize: "1.1rem",
    fontWeight: "bold",
    textDecoration: "none",
  }),
  period: (theme) => ({
    fontSize: "0.9rem",
    color: theme === "dark" ? "#ccc" : "#666",
    marginBottom: "0.5rem",
    fontStyle: "italic",
  }),
  description: (theme) => ({
    fontSize: "0.95rem",
    color: theme === "dark" ? "#aaa" : "#555",
    marginBottom: "1rem",
    lineHeight: "1.5",
  }),
  techStack: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.5rem",
  },
  arrowIcon: (theme) => ({
    position: "absolute",
    top: "1rem",
    right: "1rem",
    color: theme === "dark" ? "#ccc" : "#666",
    transition: "color 0.3s",
  }),
  cardHeader: (theme) => ({
    display: "flex",
    alignItems: "center",
    gap: "1rem",
    marginBottom: "1rem",
  }),
};